card/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.CardLibrary.as_view(), name="home"),
    path("<str:card_id>/", views.card_detail, name="card_detail")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("deckbuilder/", include("deckbuilder.urls"), name="deckduilder-urls"),
    path("accounts/", include("allauth.urls")),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path("", include("card.urls"), name="card-urls"),
]

deckbuilder/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.deckbuilder, name='deckbuilder'),
    path('decks/', views.DeckList.as_view(), name='deck_list'),
    path('my-decks/', views.MyDecks.as_view(), name='my_decks'),
    path('<int:deck_id>/', views.deck_detail, name='deck_detail'),
    path('<int:deck_id>/edit/',views.edit_deck, name='edit_deck'),
    path('<int:deck_id>/delete/',views.delete_deck, name='delete_deck'),
]

card/models.py
from django.db import models
from cloudinary.models import CloudinaryField

# Create your models here.
class Card(models.Model):
    card_id = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=200)
    card_image = CloudinaryField('image', default='placeholder')
    class Meta:
        ordering = ["card_id"]
    def __str__(self):
        return f"{self.name}"

deckbuilder/models.py
from django.db import models
from django.contrib.auth.models import User

STATUS = ((0, "Private"), (1, "Public"))

# Create your models here.
class Deck(models.Model):
    deck_name = models.CharField(max_length=20)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="saved_decks"
    )
    deck_content = models.TextField()
    published = models.IntegerField(choices=STATUS, default=0)
    additional_info = models.TextField(blank=True)
    updated_on = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ["-updated_on"]
    def __str__(self):
        return f"{self.deck_name}"
    

deckbuilder/forms.py
from .models import Deck
from django import forms


class DeckForm(forms.ModelForm):
    class Meta:
        model = Deck
        fields = ("deck_name","deck_content","additional_info","published",)

card/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic
from django.contrib import messages
from django.http import HttpResponseRedirect
from .models import Card

# Create your views here.


class CardLibrary(generic.ListView):
    """
    Dispalys the card library
    """
    queryset = Card.objects.all()
    template_name = "card/card_library.html"


def card_detail(request, card_id):
    """
    Display an individual :model:`card.Card`.

    **Context**

    ``card``
        An instance of :model:`card.Card`.

    **Template:**

    :template:`card/card_detail.html`
    """
    queryset = Card.objects.all()
    card = get_object_or_404(queryset, card_id=card_id)

    return render(
        request,
        "card/card_detail.html",
        {"card": card},
    )

deckbuilder/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from .models import Deck
from .forms import DeckForm
from card.models import Card


# Create your views here.
class DeckList(generic.ListView):
    """
    displays all public decks
    """
    queryset = Deck.objects.filter(published=1)
    template_name = "deckbuilder/deck_list.html"
    paginate_by = 12

class MyDecks(LoginRequiredMixin, generic.ListView):
    """
    displays all of user's decks
    """
    template_name = "deckbuilder/my_decks.html"
    paginate_by = 12

    def get_queryset(self):
        return Deck.objects.filter(author=self.request.user)
    

@login_required
def deckbuilder(request):
    """
    Builds a deck as :model:`deckbuilder.Deck`.
    Displays cards to choose from :model:`card.Card`.

    **Context**
    ``deck_form``
        An instance of :form:`deckbuilder.DeckForm`

    ``cards``
        An instance of :model:`card.Card`.

    **Template:**

    :template:`deckbuilder/deckbuilder.html`
    """
    cards = Card.objects.all()
    deck_form = DeckForm()

    if request.method == "POST":
        deck_form = DeckForm(data=request.POST)
        if deck_form.is_valid():
            saved_deck = deck_form.save(commit=False)
            saved_deck.author = request.user
            saved_deck.save()
            messages.add_message(
                request, messages.SUCCESS,
                'Deck saved successfully'
            )
            return HttpResponseRedirect(reverse('deck_detail', args=[saved_deck.id]))
        else:
            messages.add_message(
                request, messages.ERROR,
                'Error while saving deck'
            )

    return render(
        request,
        "deckbuilder/deckbuilder.html",
        {
            "cards": cards,
            "deck_form": deck_form
        },
    )


def deck_detail(request, deck_id):
    """
    Display an individual :model:`deckbuilder.Deck`

    **Context**

    ``deck``
        An instance of :model:`deckbuilder.Deck`.
    ``deck_cards``
        A queryset of :model:`card.Card` instances.

    **Template:**

    :template:`deckbuilder/deck_detail.html`
    """
    deck = get_object_or_404(Deck, id=deck_id)
    card_ids = deck.deck_content.split(',')
    deck_cards = [Card.objects.get(card_id=card_id) for card_id in card_ids]
    return render(
        request,
        "deckbuilder/deck_detail.html",
        {
            "deck": deck,
            "deck_cards": deck_cards
        },
    )


def edit_deck(request, deck_id):
    """
    Edits an instance of :model:`deckbuilder.Deck`

    **Context**

    ``deck``
        The targeted instance of :model:`deckbuilder.Deck`.

    ``deck_form``
        An instance of :form:`deckbuilder.DeckForm`
    """

    deck = get_object_or_404(Deck, id=deck_id)
    cards = Card.objects.all()
    card_ids = deck.deck_content.split(',')
    deck_cards = [Card.objects.get(card_id=card_id) for card_id in card_ids]

    if request.method == "POST":
        deck_form = DeckForm(data=request.POST, instance=deck)

        if deck_form.is_valid() and deck.author == request.user:
            saved_deck = deck_form.save(commit=False)
            saved_deck.author = request.user
            saved_deck.save()
            messages.add_message(
                request, messages.SUCCESS,
                'Deck updated successfully'
            )
            return HttpResponseRedirect(reverse('deck_detail', args=[saved_deck.id]))
        else:
            messages.add_message(
                request, messages.ERROR,
                'Error while updating deck'
            )

    deck_form = DeckForm(instance=deck)

    return render(
        request,
        "deckbuilder/deckbuilder.html",
        {
            "cards": cards,
            "deck": deck,
            "deck_form": deck_form,
            "deck_cards": deck_cards,
            "edit_mode": True,
        },
    )

def delete_deck(request, deck_id):
    """
    Deletes an instance of :model:`deckbuilder.Deck`

    **Context**

    ``deck``
        The targeted instance of :model:`deckbuilder.Deck`.
    """

    deck = get_object_or_404(Deck, id=deck_id)

    if deck.author == request.user:
        deck.delete()
        messages.add_message(
                request, messages.SUCCESS,
                'Deck deleted successfully'
            )
        return HttpResponseRedirect(reverse('my_decks'))
    else:
        messages.add_message(
                request, messages.SUCCESS,
                'Error while deleting deck'
            )

card/templates/card/card_detail.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 col-lg-6 mt-3">
            <img src="{{ card.card_image.url }}" alt="{{ card.name }}">
        </div>
        <div class="col-12 col-lg-6 card-description mt-3">
            <h2>{{card.name}}</h2>
            <br>
            <ul>
                <li></li>
            </ul>
            
        </div>
    </div>
</div>
{% endblock %}

card/templates/card/card_library.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row library">
        {% for card in card_list %}
        <div class="col-12 col-md-4 col-lg-2 my-2">
            <a href="{% url 'card_detail' card.card_id %}">
                <img class="library-img" src="{{ card.card_image.url }}" alt="{{ card.name }}">
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

deckbuilder/templates/deckbuilder/deck_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container deck-detail my-1 pb-2">    
    <div class="deck-display-header py-2">
        <img src="{% static 'images/pokeball.png' %}" alt="pokeball" class="me-3">
        <h1 class="h3 m-0">{{deck.deck_name}}</h1>
        {% if deck.author == request.user %}
        <a href="{% url 'edit_deck' deck.id %}" class="btn btn-primary ms-auto">Edit</a>
        {% endif %}
    </div>
    <div class="row mx-3 py-2 deck-display">
        {% for card in deck_cards %}
        <div class="col-12 col-md-4 col-lg-2 my-2">
            <img class="library-img" src="{{ card.card_image.url }}" alt="{{ card.name }}">
        </div>
        {% endfor %}
    </div>
    
</div>

{% endblock %}

deckbuilder/templates/deckbuilder/deck_list.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row library">
        {% for deck in deck_list %}
        <div class="col-12 col-md-4 my-2">
            <div class = "deck-list-items px-2">
                <div class="deck-list-name">
                    <a href="{% url 'deck_detail' deck.id %}">
                        <strong>{{deck.deck_name}}</strong> by {{deck.author}}
                    </a>
                </div>
            </div>
            
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

deckbuilder/templates/deckbuilder/deckbuilder.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="deckbuilder my-3 p-3">
        <h1>{% if edit_mode %}Edit{% else %}Build{% endif %} Your Deck</h1>
        <form method="post">
            {% csrf_token %}
            <div>
                <label for="{{ deck_form.deck_name.id_for_label }}">Deck Name:</label>
                {{ deck_form.deck_name }}
            </div>
            <div class="hidden">
                {{ deck_form.deck_content }}
            </div>
            <div class="deck-area row"> 
                <!-- Cards will be appended here -->
                {% if edit_mode %}
                    {% for card in deck_cards %}
                    <div class="col-12 col-md-4 col-lg-2 my-2">
                        <img class="deck-img" src="{{ card.card_image.url }}" data-card-id="{{ card.card_id }}" alt="{{ card.name }}">
                    </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div>
                <label for="{{ deck_form.additional_info.id_for_label }}">Additional Information:</label><br>
                {{ deck_form.additional_info }}
            </div>
            <div>
                <label for="{{ deck_form.published.id_for_label }}">Published:</label>
                {{ deck_form.published }}
            </div>
            <button type="submit" class="btn btn-primary mt-2">{% if edit_mode %}Update{% else %}Save{% endif %} Deck</button>
        </form>
        {% if edit_mode %}
        <button type="submit" class="btn btn-danger mt-2 delete-deck">Delete Deck</button>
        {% endif %}
    </div>

    <div class="library row">
        {% for card in cards %}
        <div class="col-12 col-md-4 col-lg-2 my-2">
            <img class="library-img" src="{{ card.card_image.url }}" data-card-id="{{card.card_id}}" alt="{{card.name}}">
        </div>
        {% endfor %}
    </div>
</div>


<!-- Delete confirmation modal -->
<div id="delete-modal" class="hidden">
    <div id="delete-modal-content">
        
        <div class="custom-modal-header px-2">
            <h5 class="m-0">Delete Deck</h5>
            <button type="button" class="btn-close close-button ms-auto" aria-label="Close"></button>
        </div>
        <div class="px-3 my-2">
            Are you sure you want to delete your deck?
            This action cannot be undone.
        </div>
        <div>
            <button type="button" class="btn btn-secondary close-button me-2">Close</button>
            <a id="delete-confirm" {% if edit_mode %} href="{% url 'delete_deck' deck.id %}" {% endif %} class="btn
            btn-danger">Delete</a>
        </div>

    </div>
</div>

{% endblock %}

{% block js %}
<!-- Custom Js -->
<script src="{% static 'js/deckbuilder.js' %}"></script>
{% endblock %}

deckbuilder/templates/deckbuilder/my_decks.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row library">
        {% for deck in deck_list %}
        <div class="col-12 col-md-4 my-2">
            <div class = "deck-list-items px-2">
                <div class="deck-list-name">
                    <a href="{% url 'deck_detail' deck.id %}">
                        <strong>{{deck.deck_name}}</strong>
                    </a>
                </div>
            </div>
            
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/base.html
{% load static %}

{% url 'home' as home_url %}
{% url 'deckbuilder' as deckbuilder_url %}
{% url 'deck_list' as deck_list_url %}
{% url 'my_decks' as my_decks_url %}
{% url 'account_login' as login_url %}
{% url 'account_signup' as signup_url %}
{% url 'account_logout' as logout_url %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Favicon -->
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon-16x16.png' %}">
  <title>Pokedeckz</title>
  <!-- Boostrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body class="d-flex flex-column min-vh-100">

  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg sticky-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">PokeDeckz</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link {% if request.path == home_url %}active{% endif %}" href="{% url 'home' %}">Card
              Library</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == deck_list_url %}active{% endif %}"
              href="{% url 'deck_list' %}">Decks</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == my_decks_url %}active{% endif %}"
              href="{% url 'my_decks' %}">My
              Decks</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == deckbuilder_url %}active{% endif %}"
              href="{% url 'deckbuilder' %}">Build Your Deck</a>
          </li>
        </ul>
        <ul class="navbar-nav">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link {% if request.path == logout_url %}active{% endif %}" aria-current="page"
              href="{% url 'account_logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link {% if request.path == signup_url %}active{% endif %}" aria-current="page"
              href="{% url 'account_signup' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == login_url %}active{% endif %}" aria-current="page"
              href="{% url 'account_login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <!-- Main Content -->
  <main class="pb-2">
    <!-- displaying Django messages -->
    <div class="container">
      <div class="row">
        <div class="col-md-8 offset-md-2">
          {% for message in messages %}
          <div class="alert {{ message.tags }} alert-dismissible
                fade show" id="msg" role="alert">
            {{ message | safe }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
    {% block content %}
    {% endblock %}
  </main>


  <!-- Footer -->
  <footer class="mt-auto">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <p><i class="fa-regular fa-copyright"></i> All Pokémon images, names, characters, and related marks are
            trademarks and copyright of The Pokémon Company, Nintendo, Game Freak, or Creatures Inc. (“Pokémon Rights
            Holders”).</p>
        </div>
        <div class="col-12">
          <p>Github Repository:</p>
          <a href="https://github.com/KelvinC181/Pokedeckz-re" target="blank"><i class="fa-brands fa-github"></i></a>
        </div>
      </div>
    </div>
  </footer>

  {% block js %}
  {% endblock %}
  <!-- Bootstrap Script -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
  <!-- Font Awesome Script -->
  <script src="https://kit.fontawesome.com/67187a987e.js" crossorigin="anonymous"></script>
</body>

</html>

templates/mfa/authenticate.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Sign In" %}
{% endblock head_title %}
{% block content %}
    <h1>{% trans "Two-Factor Authentication" %}</h1>
    <p>
        {% blocktranslate %}Your account is protected by two-factor authentication. Please enter an authenticator code:{% endblocktranslate %}
    </p>
    <form class="authenticate"
          method="POST"
          action="{% url 'mfa_authenticate' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Sign In" %}</button>
    </form>
{% endblock content %}

templates/mfa/index.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Two-Factor Authentication" %}
{% endblock head_title %}
{% block content %}
    <h1>{% trans "Two-Factor Authentication" %}</h1>
    <section class="totp">
        <h2>{% translate "Authenticator App" %}</h2>
        {% if authenticators.totp %}
            <p>{% translate "Authentication using an authenticator app is active." %}</p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_deactivate_totp' %}">{% translate "Deactivate" %}</a>
                </li>
            </ul>
        {% else %}
            <p>{% translate "An authenticator app is not active." %}</p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_activate_totp' %}">{% translate "Activate" %}</a>
                </li>
            </ul>
        {% endif %}
    </section>
    <section class="recovery_codes">
        <h2>{% translate "Recovery Codes" %}</h2>
        {% if authenticators.recovery_codes %}
            <p>
                {% blocktranslate with total_count=authenticators.recovery_codes.generate_codes|length count unused_count=authenticators.recovery_codes.get_unused_codes|length %}There is {{ unused_count }} out of {{ total_count }} recovery codes available.{% plural %}There are {{ unused_count }} out of {{ total_count }} recovery codes available.{% endblocktranslate %}
            </p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_view_recovery_codes' %}">{% translate "View codes" %}</a>
                </li>
                <li>
                    <a href="{% url 'mfa_download_recovery_codes' %}">{% translate "Download codes" %}</a>
                </li>
                <li>
                    <a href="{% url 'mfa_generate_recovery_codes' %}">{% translate "Generate new codes" %}</a>
                </li>
            </ul>
        {% else %}
            <p>{% translate "No recovery codes set up." %}</p>
        {% endif %}
    </section>
{% endblock content %}

templates/mfa/recovery_codes/base.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Recovery Codes" %}
{% endblock head_title %}

templates/mfa/recovery_codes/generate.html
{% extends "mfa/recovery_codes/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% translate "Recovery Codes" %}</h1>
    <p>
        {% blocktranslate %}You are about to generate a new set of recovery codes for your account. This action will invalidate your existing codes. Are you sure?{% endblocktranslate %}
    </p>
    <form method="POST" action="{% url 'mfa_generate_recovery_codes' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Generate" %}</button>
    </form>
{% endblock content %}

templates/mfa/recovery_codes/index.html
{% extends "mfa/recovery_codes/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% translate "Recovery Codes" %}</h1>
    <p>
        {% blocktranslate count unused_count=unused_codes|length %}There is {{ unused_count }} out of {{ total_count }} recovery codes available.{% plural %}There are {{ unused_count }} out of {{ total_count }} recovery codes available.{% endblocktranslate %}
    </p>
    {% if unused_codes %}
        <textarea class="recovery-codes" rows="{{ unused_codes|length }}" readonly>{% for code in unused_codes %}{{ code }}
{% endfor %}
</textarea>
    {% endif %}
    <ul class="actions">
        {% if unused_codes %}
            <li>
                <a href="{% url 'mfa_download_recovery_codes' %}">{% translate "Download codes" %}</a>
            </li>
        {% endif %}
        <li>
            <a href="{% url 'mfa_generate_recovery_codes' %}">{% translate "Generate new codes" %}</a>
        </li>
    </ul>
{% endblock content %}

templates/mfa/totp/activate_form.html
{% extends "mfa/totp/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% trans "Activate Authenticator App" %}</h1>
    {{ totp_svg|safe }}
    <form method="POST" action="{% url 'mfa_activate_totp' %}">
        {% csrf_token %}
        <p>
            <label>{% translate "Authenticator secret" %}:</label>
            <input type="text"
                   disabled="disabled"
                   value="{{ form.secret }}"
                   size="{{ form.secret|length }}">
        </p>
        {{ form.as_p }}
        <button type="submit">{% trans "Activate" %}</button>
    </form>
{% endblock content %}

templates/mfa/totp/base.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Authenticator App" %}
{% endblock head_title %}

templates/mfa/totp/deactivate_form.html
{% extends "mfa/totp/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% trans "Deactivate Authenticator App" %}</h1>
    <p>
        {% blocktranslate %}You are about to deactivate authenticator app based authentication. Are you sure?{% endblocktranslate %}
    </p>
    <form method="POST" action="{% url 'mfa_deactivate_totp' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Deactivate" %}</button>
    </form>
{% endblock content %}